### ISSUE TITLE
Questions about the approach and future of this project

### ISSUE THREAD

**Issue by whereswaldon** [benoitkugler/textlayout#3]
Hello! This work is really exiting and interesting. I'm one of the maintainers of [Gio](https;//gioui.org), and both we and the [Fyne](https://fyne.io/) toolkit have been searching for a way to achieve HarfBuzz's functionality without losing portability. A port of HarfBuzz to Go is one of the things we considered, but we thought it was likely too much effort to create and maintain to be realistic.

That being said, @sbinet stumbled across this repository, and it seems to be doing that very thing, so I'm opening this issue as a public place to ask some questions about your work:

1. How are you planning to license the project? It doesn't seem to have a License right now.
2. How are you "porting" the Harfbuzz code? Is it all manual, or do you have some kind of automation in place for translating the C++ into Go?
3. What is your planned scope for the project? Are you shooting for total parity with HarfBuzz, or some subset of its features?

My goal with asking these is really to see whether there's enough alignment between your project goals and those of Gio/Fyne for a collaboration to make sense. I'm not trying to ask you to do a bunch of work on our behalf, and I hope that's clear.

Regardless of the answers to the above, thanks for plumbing these depths on behalf of Gophers everywhere!

**Comment by benoitkugler** [comment]
Hi,

This project was kind of a challenge to see if I could write something useful on a non easy task. I don't have any specific goal in mind, apart from reaching a "functional" package. By that, I mean ideally being able to load fonts and layout text with the Pango API (which calls Harfbuzz). So, to answer your third question, that involves the main HarfBuzz functionalities.
Overall, I would be glad if this package could contribute to the GUI in Go ecosystem !
As longer term goal, I was also thinking to some project like https://github.com/Kozea/WeasyPrint which enables to convert from HTML markup to a laid out PDF. I've actually started a port, and one of the key required functionality is also text layout (Pango/Harfbuzz being used in the Python library).

I port the HarfBuzz manually (copying, pasting, formatting, renaming) and I try to stay closer to the source. However, I have prioritized simplicity over performance so far.

Regarding the license, I would indeed like to license the project with something permissive. To be honest, I have not done it yet because I'm not sure how "porting code" is considered as far as licence are concerned.

**Comment by whereswaldon** [comment]
> I port the HarfBuzz manually (copying, pasting, formatting, renaming) and I try to stay closer to the source. However, I have prioritized simplicity over performance so far.

I worry that this strategy will make it difficult to maintain as HarfBuzz evolves. As I understand it, the HarfBuzz code is updated very regularly. Do you have plans for how to handle that?

> Regarding the license, I would indeed like to license the project with something permissive. To be honest, I have not done it yet because I'm not sure how "porting code" is considered as far as licence are concerned.

This is a valid concern. I think there should be no issue with using the [same license as HarfBuzz](https://github.com/harfbuzz/harfbuzz/blob/master/COPYING), except that it is very complicated. Figuring this out will probably require some research on how other source-based ports have chosen their licenses.

> Overall, I would be glad if this package could contribute to the GUI in Go ecosystem!

That's good to know! I think we're mostly worried about these aspects of a solution (there may be other constraints that I haven't thought of):

- graphics-output-independent API (so that it can be consumed by Gio, Fyne, and your Pango API)
- feature-completeness such that we can render all of the same scripts and languages as HarfBuzz
- some level of automation to ensure that we can keep up with upstream HarfBuzz as it changes and evolves
- sufficiently permissive licensing that the core libraries of our toolkits can add it as a dependency without changing their licenses in turn.

You can read about the investigation/thinking Gio has already put into this subject [here](https://todo.sr.ht/~eliasnaur/gio/146).

Thank you for working on this, and thank you for answering my questions! If you'd like to get in touch more synchronously, you can find us in the `#gioui` and `#fyne` slack channels on gophers.slack.com. We should definitely keep talking about this!

**Comment by tdewolff** [comment]
This is a grand project and it's great that you're interested in making a Go port of HarfBuzz and FriBidi! This will definitively be very useful for [tdewolff/canvas](https://github.com/tdewolff/canvas), which currently requires CGO for such support. To be honest I don't think it is feasible to match HarfBuzz nor is it desirable to replicate its results. That would be a massive amount of work in duplex, alongside HarfBuzz itself, and is bound to have divergences. I would already be happy if this port would cover 90% of the cases. Using the GPOS and GSUB tables should get you quite far already, if it helps you can check out my work on parsing various font file formats at https://github.com/tdewolff/canvas/tree/master/font (all SFNT fonts such as TTF, OTF, WOFF, WOFF2, and EOT, working on Type1 PFA/PFB support too).

**Comment by sbinet** [comment]
@tdewolff 
> working on Type1 PFA/PFB support 

ah? having a BSD/MIT-based package supporting Type1 fonts is the last remaining roadblock for "my" pure-Go TeX->DVI->(PNG,PDF) pipeline...
- https://todo.sr.ht/~sbinet/star-tex/11
(_ie:_ pretty interested to follow this side of your project as well :})

**Comment by tdewolff** [comment]
Yes, I've been looking at your project recently, good stuff! The PFA/PFB parsers should be really a piece of cake compared to the SFNT parser and all its tables. Besides, the base work is there as I already have a working PostScript Type1 string parser for the CFF and CFF2 tables. The other idea I have is to also add a DVI render target (and an OpenVG, Fyne, and other rendering targets). Soon I also intend to have a native Go LaTeX equation parser and renderer using your libraries.

**Comment by benoitkugler** [comment]
> This is a grand project and it's great that you're interested in making a Go port of HarfBuzz and FriBidi! This will definitively be very useful for [tdewolff/canvas](https://github.com/tdewolff/canvas), which currently requires CGO for such support. To be honest I don't think it is feasible to match HarfBuzz nor is it desirable to replicate its results. That would be a massive amount of work in duplex, alongside HarfBuzz itself, and is bound to have divergences. I would already be happy if this port would cover 90% of the cases. Using the GPOS and GSUB tables should get you quite far already, if it helps you can check out my work on parsing various font file formats at https://github.com/tdewolff/canvas/tree/master/font (all SFNT fonts such as TTF, OTF, WOFF, WOFF2, and EOT, working on Type1 PFA/PFB support too).

I think the current implementation has almost feature parity with Harfbuzz, since the tests from https://github.com/harfbuzz/harfbuzz/tree/master/test/shaping are passing. The main exception is the support for Graphite fonts, which requires a dedicated tool.

Actually, I also implemented some font supports in [fonts](https://github.com/benoitkugler/textlayout/tree/main/fonts) (truetype, type1, CFF, bitmap (pcf)). Should we think about merging our implementation in some way ? 
There is a current reflexion about a shared go package for [text layout](https://github.com/go-text/shaping) so maybe this would be the place to do so ?

**Comment by benoitkugler** [comment]
> That's great to hear! I've added support for your work as the default implementation, but it is possible to opt for the CGO bindings as well using the harfbuzz and fribidi build tags. See tdewolff/canvas@9aae30b. I've however noticed that your work differs in the cluster values returned for each glyph when using MonotoneCharacters. The cluster values don't seem to match the byte-indices, as does the original HarfBuzz.

Great to here as well ! 

I've chosen to use rune slices instead of strings, so it is expected that the default cluster value are not byte indices but rune indices. It is possible to set the cluster values using `Buffer.AddRune`. Let me know if this is a problem : I can add a Buffer.AddString (or AddBytes) if needed.

By the way, If you detect other change with the original implementation, let me know so that I can write a test and fix the problem :)

(And just to be explicit, the API of this module is still experimental, and will probably change, so you should expect breaking changes.)

**Comment by gedw99** [comment]
totally out of the left field but there is a WASM of halfbuzz at https://github.com/harfbuzz/harfbuzzjs/releases

golang can run WASM via wasmer as we all know.

Its a different way to skin the cat i know.

**Comment by benoitkugler** [comment]
See [go-text](https://github.com/go-text/typesetting) for more information.
